### PR TITLE
Snare Flying Fix

### LINKED ISSUE #6: Monsters with Snare should not be able to miss against a monster with Flying
The following is based on the information found here: https://support.splinterlands.com/hc/en-us/articles/4414362714644-Attack-Accuracy

In the following battle I saw Sand Worm miss an attack against Spark Pixies. This should not be possible. https://splintertools.io/battle?player=epicraptor&battleId=sl_93fe57219d89096720c978ada00fc332

### PR DESCRIPTION
**Pull request by IProto**
Fixed: Monsters with Snare can no longer miss attacks against monster…

### CODE REVIEW

File: src/utils/game_utils.ts [hunk 1]
```diff
@@ -14,6 +14,9 @@ export function getDidDodge(
   if (attackingMonster.hasAbility(Ability.TRUE_STRIKE)) {
     return false;
   }
+  if (attackingMonster.hasAbility(Ability.SNARE) && attackTarget.hasAbility(Ability.FLYING)) {
```
Comment (thechungster) [inline src/utils/game_utils.ts:17]: `attackTarget.hasAbility(Ability.FLYING) && attackTarget.hasDebuff(Ability.SNARE)`

When a monster is snared it gets the snare debuff and all monsters will be able to hit it regardless of whether or not the attacking monster has snare. The snare debuff is added before this dodge check

**Comment by thechungster** [comment]
Could you remove the snare checks below since they're obsolete now?

https://github.com/thechungster/splinterlands-simulator/blob/master/src/utils/game_utils.ts#L29-L31

File: src/utils/game_utils.ts (hunk 1 above)
Comment (IProto) [reply src/utils/game_utils.ts:17]: It makes sense that the attackTarget monster would have the debuff but they need to actually be hit before that could happen. This check is simply to ensure that the initial hit happens so snare is actually applied and all subsequent attacks from monsters with snare should also hit it 100% of the time.

Some of the logic later with the snare check I believe still applies. Attacking monsters without snare aren't guaranteed to hit a monster with a snare debuff. They can just attack with the same chance to hit as if they didn't have flying. We can get rid of this bit since it can't happen anymore: `!attackingMonster.hasAbility(Ability.SNARE) &&`

Hopefully that all makes sense. TLDR; I think the logic I have on line 17 is still accurate but we can get rid of the redundant snare check on line 33.

Comment (thechungster) [reply src/utils/game_utils.ts:17]: Got it, I mistakenly read the ability as "all flying monsters that are snared would always hit"

**Review by thechungster — APPROVED** [review]
